import type { SimulationState, Vendor, Incident } from '@/engine/types';

const vendors: Vendor[] = [
  {
    id: 'v1',
    name: 'CloudSync Pro',
    status: 'active',
    securityRating: 92,
    riskLevel: 'low',
    compliance: { NIST: true, ISO27001: true, SOC2: true, GDPR: true },
    lastAssessment: '2026-01-15',
    category: 'Cloud Infrastructure',
    contractValue: 250000,
    dataAccess: 'extensive',
  },
  {
    id: 'v2',
    name: 'DataVault Systems',
    status: 'active',
    securityRating: 78,
    riskLevel: 'medium',
    compliance: { NIST: true, ISO27001: true, SOC2: false, GDPR: true },
    lastAssessment: '2026-01-10',
    category: 'Data Storage',
    contractValue: 180000,
    dataAccess: 'extensive',
  },
  {
    id: 'v3',
    name: 'SecureAuth Inc',
    status: 'active',
    securityRating: 95,
    riskLevel: 'low',
    compliance: { NIST: true, ISO27001: true, SOC2: true, GDPR: true },
    lastAssessment: '2026-01-18',
    category: 'Identity Management',
    contractValue: 120000,
    dataAccess: 'moderate',
  },
  {
    id: 'v4',
    name: 'NetFlow Analytics',
    status: 'at-risk',
    securityRating: 45,
    riskLevel: 'high',
    compliance: { NIST: false, ISO27001: false, SOC2: false, GDPR: true },
    lastAssessment: '2025-12-20',
    category: 'Analytics',
    contractValue: 75000,
    dataAccess: 'limited',
  },
  {
    id: 'v5',
    name: 'PaySecure Global',
    status: 'active',
    securityRating: 88,
    riskLevel: 'low',
    compliance: { NIST: true, ISO27001: true, SOC2: true, GDPR: true },
    lastAssessment: '2026-01-12',
    category: 'Payment Processing',
    contractValue: 450000,
    dataAccess: 'extensive',
  },
  {
    id: 'v6',
    name: 'CommHub Solutions',
    status: 'under-review',
    securityRating: 62,
    riskLevel: 'medium',
    compliance: { NIST: true, ISO27001: false, SOC2: false, GDPR: true },
    lastAssessment: '2026-01-05',
    category: 'Communications',
    contractValue: 95000,
    dataAccess: 'moderate',
  },
  {
    id: 'v7',
    name: 'LogiTrack Pro',
    status: 'active',
    securityRating: 71,
    riskLevel: 'medium',
    compliance: { NIST: true, ISO27001: true, SOC2: false, GDPR: false },
    lastAssessment: '2026-01-08',
    category: 'Logistics',
    contractValue: 65000,
    dataAccess: 'limited',
  },
  {
    id: 'v8',
    name: 'CyberShield Corp',
    status: 'active',
    securityRating: 97,
    riskLevel: 'low',
    compliance: { NIST: true, ISO27001: true, SOC2: true, GDPR: true },
    lastAssessment: '2026-01-19',
    category: 'Security Services',
    contractValue: 320000,
    dataAccess: 'extensive',
  },
];

const incidents: Incident[] = [
  {
    id: 'i1',
    vendorId: 'v4',
    type: 'security',
    severity: 'high',
    title: 'Unauthorized Access Attempt',
    description: 'Multiple failed authentication attempts detected from unusual IP ranges',
    timestamp: Date.now() - 3600000,
    resolved: false,
  },
  {
    id: 'i2',
    vendorId: 'v2',
    type: 'compliance',
    severity: 'medium',
    title: 'SOC2 Certification Expired',
    description: 'Vendor SOC2 Type II certification has expired and requires renewal',
    timestamp: Date.now() - 86400000,
    resolved: false,
  },
  {
    id: 'i3',
    vendorId: 'v6',
    type: 'performance',
    severity: 'low',
    title: 'API Response Degradation',
    description: 'Average API response times increased by 40% over the past week',
    timestamp: Date.now() - 172800000,
    resolved: false,
  },
];

export const initialSimulationState: SimulationState = {
  time: 0,
  vendors,
  incidents,
};
